server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  main:
    web-application-type: servlet
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${EMAIL_HOST}
application:
  security:
    jwt:
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}
        refresh-token:
            expiration: ${JWT_REFRESH_EXPIRATION}